### PR TITLE
Optimized docker build

### PR DESCRIPTION
**Pull request by JohannesEH**
The current Dockerfile is structured in a way that males the resulting image much larger than it needs to be and goes against certain best practices. For this reason I moved the Dockerfile's RUN statements into an init.sh script, and changed it a bit to improve the resulting image stats.

```
Resulting image stats:
=================================
Before change: 15 layers, 1015 MB
 After change:  3 layers,  382 MB
```

This will decrease download and unpacking times in Azure devops pipelines quite a bit. Some of the image consumers would be very happy about this change. 😉 

I also made some changes to the build itself:

1. I removed the call to `apt-get dist-upgrade` as this goes against [best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get). Instead we could choose to use a newer base image like debian:buster-slim.

2. I added `--no-install-recommends` to all `apt-get install` commands to avoid install unnecessary packages into the image. All required packages should be added explicitly.

### CODE REVIEW

**Comment by HenrikStanley** [comment]
@JohannesEH 

This is really cool, thanks for the tip.
We are in the process of moving our images to a new repo where we are changing the way we build them:
https://github.com/dfds/pipeline-docker/tree/ch2579/docker-pipeline-build-project
So the image change you suggested will likely not be build in that repo.
However, I will definitely look into incorporating the practices in our new repo where we are revamping our build images all together.
You suggestion also gave me a couple of idea's on how we could solve some issues i was dealing with in the new repo.

**Comment by kim-lindhard-dfds** [comment]
@JohannesEH What made chose to move installation of dependencies out of the dockerfile and into a script that will install the dependencies as a single layer of the docker image?

**Comment by JohannesEH** [comment]
@HenrikStanley that's fine. Please let me know if I can help. 😉 For now I guess I'll just release the slimmed down version for our pipeline.

@kim-lindhard-dfds well the thing that creates layers in Docker images are `RUN`, `ADD` & `COPY` commands. So try to minimize the use of those commands. In the future we could use the experimental option in `docker build` called `--squash`. This will essentially merge the layers after the build so we don't have to worry about layers so much. You still have to worry about the final image size, and eliminate unnecessary packages and content from your image.

**Comment by HenrikStanley** [comment]
@JohannesEH 

I have checked and checked and checked and I cannot get my image to get the same size as yours, and now I think I know why.

I think that your install of AzureCLI fails, this takes up 500 MB alone and accounts for the insane difference in image size.

Try changing the env variable for AzureCLI to:
2.5.1-1~buster

And then build yours again and check for size.
if you guys don't use the cli in the image you are consuming you can ofc just remove it from your build, but I think that is why you see such a difference as the cache simply does not account for ½ gig of space ;)

**Comment by JohannesEH** [comment]
@HenrikStanley thanks for figuring that out. I feel very embarrassed now. 🙈 

I would have caught it had I just remembered to include `set -e` in the beginning of the bash script. Oh well I suppose that's what I get deserve for trying to be smart. 🤷‍♂️ 

I looked into it a bit further. The reason why the azure-cli package is so absurdly huge is that it packs an entire version of python 3.6. If I had some more time it would be nice to see if I could get it to install from pip instead. It might make the azure-cli install simpler and make python available for other build pipeline image users as well. I mean, it seems a bit wasteful to have python lying around only for the sake of azure-cli. 😃 

Oh well, I'll close the PR and go hide in a corner.

**Pull request closed without merging**
